 async function getContent() {
   try {
    const response = await fetch('http://localhost:2811/')
   } catch (error) {
        console.log("ERROOOOOAAAAAA")
   }
 }

 getContent()

   


